### ISSUE TITLE
Website from README definetly needs to be removed

### ISSUE THREAD

**Issue by ktlinux** [f-spot/f-spot#160]
I would have written this as a comment on #32 but I guess this needs quite some maximum attention from the devs now that the development of this program started again. The website for f-spot is now NSFW and I don't think you'd like people to access this repo just to have a look on it outside working hours (or even at work, who am I to judge?).

I think you guys would rather have it removed from the README.md, but I don't mind you keeping it.

( ͡° ͜ʖ ͡°)

**Comment by decriptor** [comment]
That makes me very sad. I've updated both the README as well as wikipedia. If I missed anything please let me know.

**Comment by decriptor** [comment]
Thanks for letting me know!

**Comment by ktlinux** [comment]
great thing you updated Wikipedia as well. might serve as a good presentation for your program :D. Now all seems good. Awesome!

**Comment by ArloJamesBarnes** [comment]
seems to currently be a blank parked wix page

**Comment by decriptor** [comment]
I'm mostly given up on getting the website up and running under the old domain. I'm open to any suggestions as far as a new domain name.

**Comment by genterminl** [comment]
f-spot and fspot are both available in a number of TLDs, including .dev.  (I'm excluding the high priced options.)  I don't see any reason to insist on sticking with a .com address.

**Comment by decriptor** [comment]
@genterminl It used to be f-spot.org. I bought f-spot.app a little bit ago but haven't set anything up on it just yet. I'm open to suggestions both for other domains as well as web platform
